# Generated by Django 5.1.4 on 2025-12-04 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='assigned', max_length=20, verbose_name='Status')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('fueler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trainings', to='api.fueler', verbose_name='Fueler')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trainings', to='api.training', verbose_name='Training')),
            ],
            options={
                'verbose_name': 'Assigned Training',
                'verbose_name_plural': 'Assigned Trainings',
                'db_table': 'assigned_training',
                'ordering': ['-assigned_at'],
                'unique_together': {('fueler', 'training', 'status')},
            },
        ),
    ]
