# Generated by Django 5.1.4 on 2025-11-06 19:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_refactor_parking_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(max_length=50, unique=True, verbose_name='Equipment ID')),
                ('equipment_name', models.CharField(max_length=200, verbose_name='Equipment Name')),
                ('equipment_type', models.CharField(choices=[('fuel_truck', 'Fuel Truck'), ('tug', 'Tug'), ('gpu', 'Ground Power Unit'), ('air_start', 'Air Start Unit'), ('belt_loader', 'Belt Loader'), ('stairs', 'Passenger Stairs'), ('lavatory_service', 'Lavatory Service'), ('water_service', 'Water Service'), ('other', 'Other')], max_length=50, verbose_name='Equipment Type')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Manufacturer')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Serial Number')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service')], default='available', max_length=20, verbose_name='Status')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Last Maintenance Date')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Next Maintenance Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'db_table': 'equipment',
                'ordering': ['equipment_id'],
            },
        ),
        migrations.CreateModel(
            name='LineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('arrival_service', 'Arrival Service'), ('departure_service', 'Departure Service'), ('turnaround', 'Turnaround Service'), ('overnight', 'Overnight Service')], max_length=50, verbose_name='Service Type')),
                ('scheduled_time', models.DateTimeField(verbose_name='Scheduled Time')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Actual Start Time')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Actual End Time')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'Line Schedule',
                'verbose_name_plural': 'Line Schedules',
                'db_table': 'line_schedule',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='parkinglocation',
            options={'ordering': ['-display_order', 'location_code'], 'verbose_name': 'Parking Location', 'verbose_name_plural': 'Parking Locations'},
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='aircraft_type',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flight_number',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='gate',
        ),
        # Use conditional SQL drops to avoid failures if column already absent (e.g. on Supabase)
        migrations.RunSQL("ALTER TABLE parking_location DROP COLUMN IF EXISTS is_active CASCADE;"),
        migrations.RunSQL("ALTER TABLE parking_location DROP COLUMN IF EXISTS location_name CASCADE;"),
        migrations.RunSQL("ALTER TABLE parking_location DROP COLUMN IF EXISTS location_type CASCADE;"),
        migrations.RunSQL("ALTER TABLE parking_location DROP COLUMN IF EXISTS notes CASCADE;"),
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_type_display',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Aircraft Type (Display)'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_type_icao',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Aircraft Type (ICAO)'),
        ),
        migrations.AddField(
            model_name='flight',
            name='call_sign',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Call Sign / Flight Number'),
        ),
        migrations.AddField(
            model_name='flight',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact Name'),
        ),
        migrations.AddField(
            model_name='flight',
            name='contact_notes',
            field=models.TextField(blank=True, verbose_name='Contact Notes'),
        ),
        migrations.AddField(
            model_name='flight',
            name='created_by',
            field=models.ForeignKey(db_column='created_by_id', default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='created_flights', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='flight',
            name='created_by_source',
            field=models.CharField(choices=[('qt', 'QuickTurn'), ('front-desk', 'Front Desk'), ('line-department', 'Line Department'), ('google-calendar', 'Google Calendar')], default='line-department', max_length=20, verbose_name='Created By Source'),
        ),
        migrations.AddField(
            model_name='flight',
            name='fuel_order_notes',
            field=models.TextField(blank=True, verbose_name='Fuel Order Notes'),
        ),
        migrations.AddField(
            model_name='flight',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin',
            field=models.CharField(blank=True, max_length=100, verbose_name='Origin'),
        ),
        migrations.AddField(
            model_name='flight',
            name='passenger_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Passenger Count'),
        ),
        migrations.AddField(
            model_name='flight',
            name='services',
            field=models.JSONField(blank=True, default=list, verbose_name='Services'),
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='airport',
            field=models.CharField(default='MSO', help_text='Airport code: MSO, USFS, etc.', max_length=10, verbose_name='Airport'),
        ),
        # Replace duplicate column adds with conditional raw SQL to avoid ProgrammingError
        migrations.RunSQL("ALTER TABLE parking_location ADD COLUMN IF NOT EXISTS description TEXT DEFAULT '';"),
        migrations.RunSQL("ALTER TABLE parking_location ADD COLUMN IF NOT EXISTS gate VARCHAR(10);"),
        migrations.RunSQL("ALTER TABLE parking_location ADD COLUMN IF NOT EXISTS latitude DECIMAL(9,6);"),
        migrations.RunSQL("ALTER TABLE parking_location ADD COLUMN IF NOT EXISTS location_code VARCHAR(50);"),
        migrations.RunSQL("ALTER TABLE parking_location ADD COLUMN IF NOT EXISTS longitude DECIMAL(9,6);"),
        migrations.RunSQL("ALTER TABLE parking_location ADD COLUMN IF NOT EXISTS polygon JSONB;"),
        migrations.RunSQL("ALTER TABLE parking_location ADD COLUMN IF NOT EXISTS terminal VARCHAR(50);"),
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(db_column='aircraft_id', on_delete=django.db.models.deletion.RESTRICT, related_name='flights', to='api.aircraft', verbose_name='Aircraft'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(max_length=100, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('arrived', 'Arrived'), ('departed', 'Departed'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed'), ('planned', 'Planned')], default='scheduled', max_length=20, verbose_name='Flight Status'),
        ),
        migrations.AlterField(
            model_name='parkinglocation',
            name='display_order',
            field=models.IntegerField(default=0, help_text='0 = inactive/hidden, higher numbers = more popular (shows first in lists)', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('line', 'Line Department'), ('frontdesk', 'Front Desk')], default='line', max_length=20, verbose_name='Role'),
        ),
        migrations.AddIndex(
            model_name='parkinglocation',
            index=models.Index(fields=['airport', 'display_order'], name='parking_loc_airport_ebbf8c_idx'),
        ),
        migrations.AddIndex(
            model_name='parkinglocation',
            index=models.Index(fields=['location_code'], name='parking_loc_locatio_f5548c_idx'),
        ),
        migrations.AddField(
            model_name='lineschedule',
            name='assigned_personnel',
            field=models.ManyToManyField(blank=True, related_name='line_schedule_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Personnel'),
        ),
        migrations.AddField(
            model_name='lineschedule',
            name='equipment_used',
            field=models.ManyToManyField(blank=True, related_name='line_schedules', to='api.equipment', verbose_name='Equipment Used'),
        ),
        migrations.AddField(
            model_name='lineschedule',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_schedules', to='api.flight', verbose_name='Flight'),
        ),
        migrations.AddField(
            model_name='lineschedule',
            name='gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_schedules', to='api.terminalgate', verbose_name='Gate'),
        ),
    ]
