# Generated by Django 4.2 on 2025-11-17
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_equipment_lineschedule_alter_parkinglocation_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelerTrainingHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("completed_date", models.DateField(verbose_name="Completed Date")),
                ("expiry_date", models.DateField(verbose_name="Expiry Date")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "certified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_history_issued",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Certified By",
                    ),
                ),
                (
                    "fueler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_history",
                        to="api.fueler",
                        verbose_name="Fueler",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_history",
                        to="api.training",
                        verbose_name="Training",
                    ),
                ),
            ],
            options={
                "db_table": "fueler_training_history",
                "verbose_name": "Fueler Training History",
                "verbose_name_plural": "Fueler Training History",
                "ordering": ["-completed_date", "-created_at"],
            },
        ),
    ]
