from django.conf import settings
from django.db import migrations, models
import django.contrib.auth.models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        # Custom User model (squashed state)
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.models.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('line', 'Line Department'), ('frontdesk', 'Front Desk')], default='line', max_length=20, verbose_name='Role')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Employee ID')),
                ('is_active_fueler', models.BooleanField(default=False, verbose_name='Is Active Fueler')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[('objects', django.contrib.auth.models.UserManager())],
        ),
        migrations.CreateModel(
            name='FuelTank',
            fields=[
                ('tank_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Tank ID')),
                ('tank_name', models.CharField(max_length=100, verbose_name='Tank Name')),
                ('fuel_type', models.CharField(choices=[('jet_a', 'Jet A'), ('avgas', 'Avgas')], max_length=10, verbose_name='Fuel Type')),
                ('capacity_gallons', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacity (Gallons)')),
                ('min_level_inches', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Minimum Level (Inches)')),
                ('max_level_inches', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Maximum Level (Inches)')),
                ('usable_min_inches', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Usable Minimum (Inches)')),
                ('usable_max_inches', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Usable Maximum (Inches)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={'db_table': 'fuel_tank', 'verbose_name': 'Fuel Tank', 'verbose_name_plural': 'Fuel Tanks'},
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('tail_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Tail Number')),
                ('aircraft_type_icao', models.CharField(blank=True, default='', max_length=10, verbose_name='Aircraft Type (ICAO)')),
                ('aircraft_type_display', models.CharField(blank=True, default='', max_length=100, verbose_name='Aircraft Type (Display)')),
                ('airline_icao', models.CharField(blank=True, max_length=10, verbose_name='Airline ICAO')),
                ('fleet_id', models.CharField(blank=True, max_length=50, verbose_name='Fleet ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={'db_table': 'aircraft', 'verbose_name': 'Aircraft', 'verbose_name_plural': 'Aircraft'},
        ),
        migrations.CreateModel(
            name='TerminalGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.CharField(max_length=20, verbose_name='Terminal ID')),
                ('terminal_num', models.CharField(max_length=10, verbose_name='Terminal Number')),
                ('gate_number', models.CharField(max_length=10, verbose_name='Gate Number')),
                ('location_id', models.CharField(blank=True, max_length=50, verbose_name='Location ID')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={'db_table': 'terminal_gate', 'verbose_name': 'Terminal Gate', 'verbose_name_plural': 'Terminal Gates', 'ordering': ['display_order', 'terminal_num', 'gate_number']},
        ),
        migrations.AlterUniqueTogether(name='terminalgate', unique_together={('terminal_num', 'gate_number')}),
        migrations.CreateModel(
            name='ParkingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Simplified (no regex validator for test-only squashed migration)
                ('location_code', models.CharField(blank=True, help_text='Unique code: CAPS, alphanumeric, hyphens only. Examples: T-A1, D-1, BRETZ', max_length=50, null=True, unique=True, verbose_name='Location Code')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for map display', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for map display', max_digits=9, null=True, verbose_name='Longitude')),
                ('polygon', models.JSONField(blank=True, help_text='Array of [lat, lon] coordinates defining hangar boundaries', null=True, verbose_name='Polygon')),
                ('airport', models.CharField(default='MSO', help_text='Airport code: MSO, USFS, etc.', max_length=10, verbose_name='Airport')),
                ('terminal', models.CharField(blank=True, help_text='Terminal identifier: T, MIN, MAINT, etc.', max_length=50, null=True, verbose_name='Terminal')),
                ('gate', models.CharField(blank=True, help_text='Gate number: A1, A2, B1, B2, etc.', max_length=10, null=True, verbose_name='Gate')),
                ('display_order', models.IntegerField(default=0, help_text='0 = inactive/hidden, higher numbers = more popular (shows first in lists)', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={'db_table': 'parking_location', 'verbose_name': 'Parking Location', 'verbose_name_plural': 'Parking Locations', 'ordering': ['-display_order', 'location_code']},
        ),
        migrations.CreateModel(
            name='Fueler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fueler_name', models.CharField(max_length=100, verbose_name='Fueler Name')),
                ('handheld_name', models.CharField(blank=True, help_text='Name used on handheld devices', max_length=50, verbose_name='Handheld Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('user', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='fueler_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={'db_table': 'fueler', 'verbose_name': 'Fueler', 'verbose_name_plural': 'Fuelers'},
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=200, verbose_name='Training Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('validity_period_days', models.IntegerField(help_text='Number of days the training is valid', verbose_name='Validity Period (Days)')),
                ('aircraft_type', models.CharField(blank=True, help_text='Specific aircraft type (if applicable)', max_length=50, null=True, verbose_name='Aircraft Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={'db_table': 'training', 'verbose_name': 'Training', 'verbose_name_plural': 'Trainings'},
        ),
        migrations.CreateModel(
            name='FuelerTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(verbose_name='Completed Date')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('certified_by', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='certifications_issued', to=settings.AUTH_USER_MODEL, verbose_name='Certified By')),
                ('fueler', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='certifications', to='api.fueler', verbose_name='Fueler')),
                ('training', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='certifications', to='api.training', verbose_name='Training')),
            ],
            options={'db_table': 'fueler_training', 'verbose_name': 'Fueler Training', 'verbose_name_plural': 'Fueler Trainings', 'ordering': ['-expiry_date']},
        ),
        migrations.AlterUniqueTogether(name='fuelertraining', unique_together={('fueler', 'training')}),
        migrations.CreateModel(
            name='FuelerTrainingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(verbose_name='Completed Date')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('certified_by', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='training_history_issued', to=settings.AUTH_USER_MODEL, verbose_name='Certified By')),
                ('fueler', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='training_history', to='api.fueler', verbose_name='Fueler')),
                ('training', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='training_history', to='api.training', verbose_name='Training')),
            ],
            options={'db_table': 'fueler_training_history', 'verbose_name': 'Fueler Training History', 'verbose_name_plural': 'Fueler Training History', 'ordering': ['-completed_date', '-created_at']},
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(max_length=50, unique=True, verbose_name='Equipment ID')),
                ('equipment_name', models.CharField(max_length=200, verbose_name='Equipment Name')),
                ('equipment_type', models.CharField(choices=[('fuel_truck', 'Fuel Truck'), ('tug', 'Tug'), ('gpu', 'Ground Power Unit'), ('air_start', 'Air Start Unit'), ('belt_loader', 'Belt Loader'), ('stairs', 'Passenger Stairs'), ('lavatory_service', 'Lavatory Service'), ('water_service', 'Water Service'), ('other', 'Other')], max_length=50, verbose_name='Equipment Type')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Manufacturer')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Serial Number')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service')], default='available', max_length=20, verbose_name='Status')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Last Maintenance Date')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Next Maintenance Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={'db_table': 'equipment', 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment', 'ordering': ['equipment_id']},
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sign', models.CharField(blank=True, max_length=20, null=True, verbose_name='Call Sign / Flight Number')),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='Arrival Time')),
                ('departure_time', models.DateTimeField(verbose_name='Departure Time')),
                ('flight_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('arrived', 'Arrived'), ('departed', 'Departed'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed'), ('planned', 'Planned')], default='scheduled', max_length=20, verbose_name='Flight Status')),
                ('origin', models.CharField(blank=True, max_length=100, verbose_name='Origin')),
                ('destination', models.CharField(max_length=100, verbose_name='Destination')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Contact Name')),
                ('contact_notes', models.TextField(blank=True, verbose_name='Contact Notes')),
                ('services', models.JSONField(blank=True, default=list, verbose_name='Services')),
                ('fuel_order_notes', models.TextField(blank=True, verbose_name='Fuel Order Notes')),
                ('passenger_count', models.IntegerField(blank=True, null=True, verbose_name='Passenger Count')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by_source', models.CharField(choices=[('qt', 'QuickTurn'), ('front-desk', 'Front Desk'), ('line-department', 'Line Department'), ('google-calendar', 'Google Calendar')], default='line-department', max_length=20, verbose_name='Created By Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('aircraft', models.ForeignKey(db_column='aircraft_id', on_delete=models.deletion.RESTRICT, related_name='flights', to='api.aircraft', verbose_name='Aircraft')),
                ('created_by', models.ForeignKey(db_column='created_by_id', default=1, on_delete=models.deletion.RESTRICT, related_name='created_flights', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('location', models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=models.deletion.SET_NULL, related_name='flights', to='api.parkinglocation', verbose_name='Parking Location')),
            ],
            options={'db_table': 'flight', 'verbose_name': 'Flight', 'verbose_name_plural': 'Flights', 'ordering': ['-departure_time']},
        ),
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True, verbose_name='Ticket Number')),
                ('quantity_gallons', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity (Gallons)')),
                ('quantity_lbs', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity (Lbs)')),
                ('density', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Density')),
                ('progress', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='started', max_length=20, verbose_name='Progress')),
                ('charge_flags', models.JSONField(blank=True, default=dict, verbose_name='Charge Flags')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Assigned At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('qt_dispatch_id', models.CharField(blank=True, help_text='QT Technologies API dispatch ID', max_length=100, null=True, verbose_name='QT Dispatch ID')),
                ('qt_sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='QT Sync Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='fuel_transactions', to='api.flight', verbose_name='Flight')),
            ],
            options={'db_table': 'fuel_transaction', 'verbose_name': 'Fuel Transaction', 'verbose_name_plural': 'Fuel Transactions', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='FuelerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('fueler', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='assignments', to='api.fueler', verbose_name='Fueler')),
                ('transaction', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='fueler_assignments', to='api.fueltransaction', verbose_name='Transaction')),
            ],
            options={'db_table': 'fueler_assignment', 'verbose_name': 'Fueler Assignment', 'verbose_name_plural': 'Fueler Assignments', 'ordering': ['-assigned_at']},
        ),
        migrations.AlterUniqueTogether(name='fuelerassignment', unique_together={('transaction', 'fueler')}),
        migrations.CreateModel(
            name='LineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('arrival_service', 'Arrival Service'), ('departure_service', 'Departure Service'), ('turnaround', 'Turnaround Service'), ('overnight', 'Overnight Service')], max_length=50, verbose_name='Service Type')),
                ('scheduled_time', models.DateTimeField(verbose_name='Scheduled Time')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Actual Start Time')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Actual End Time')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('equipment_used', models.ManyToManyField(blank=True, related_name='line_schedules', to='api.equipment', verbose_name='Equipment Used')),
                ('assigned_personnel', models.ManyToManyField(blank=True, related_name='line_schedule_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Personnel')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='line_schedules', to='api.flight', verbose_name='Flight')),
                ('gate', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='line_schedules', to='api.terminalgate', verbose_name='Gate')),
            ],
            options={'db_table': 'line_schedule', 'verbose_name': 'Line Schedule', 'verbose_name_plural': 'Line Schedules', 'ordering': ['-scheduled_time']},
        ),
        # Indexes for ParkingLocation
        migrations.AddIndex(
            model_name='parkinglocation',
            index=models.Index(fields=['airport', 'display_order'], name='api_parking_airport_display_idx'),
        ),
        migrations.AddIndex(
            model_name='parkinglocation',
            index=models.Index(fields=['location_code'], name='api_parking_location_code_idx'),
        ),
    ]
